# 添加第四批16个超级动态涂装配置（_ex4系列）

paint_configs = {
    "striker_ex4": {
        "name": "液态金属·活体机械",
        "desc": "流动的液态金属，自由变形，呼吸般的韵律，生命与机械的完美融合",
        "neon_color": (180, 180, 200),
        "accent_color": (220, 220, 240),
        "trail_color": (160, 160, 180),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "liquid_metal",
        "particle_count": 165,
        "category": "exclusive",
        "trail_width": 21,
        "exclusive_plane": "striker",
        "model_style": "striker_ex4",
        "animated": True,
    },
    "phantom_ex4": {
        "name": "彩虹漩涡·光谱风暴",
        "desc": "七彩光谱旋转交织，色彩在空间中舞动，每个角度都是不同的颜色",
        "neon_color": (255, 100, 150),
        "accent_color": (100, 200, 255),
        "trail_color": (200, 255, 100),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "spectrum_vortex",
        "particle_count": 175,
        "category": "exclusive",
        "trail_width": 23,
        "exclusive_plane": "phantom",
        "model_style": "phantom_ex4",
        "animated": True,
    },
    "titan_ex4": {
        "name": "熔岩巨兽·地核之怒",
        "desc": "熔岩般的能量在体内流动，岩浆脉动，火山喷发般的力量",
        "neon_color": (255, 80, 0),
        "accent_color": (255, 150, 50),
        "trail_color": (200, 50, 0),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "magma_flow",
        "particle_count": 180,
        "category": "exclusive",
        "trail_width": 24,
        "exclusive_plane": "titan",
        "model_style": "titan_ex4",
        "animated": True,
    },
    "thunderbird_ex4": {
        "name": "等离子生命·电弧之魂",
        "desc": "纯粹的等离子态能量生命体，电弧跳跃，能量闪烁不定",
        "neon_color": (100, 255, 255),
        "accent_color": (255, 255, 150),
        "trail_color": (150, 200, 255),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "plasma_arc",
        "particle_count": 185,
        "category": "exclusive",
        "trail_width": 20,
        "exclusive_plane": "thunderbird",
        "model_style": "thunderbird_ex4",
        "animated": True,
    },
    "viper_ex4": {
        "name": "生物荧光·深海幻影",
        "desc": "深海生物的荧光效果，波动脉冲，渐变色彩如水母般飘逸",
        "neon_color": (0, 255, 200),
        "accent_color": (100, 150, 255),
        "trail_color": (50, 200, 180),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "bioluminescence",
        "particle_count": 170,
        "category": "exclusive",
        "trail_width": 22,
        "exclusive_plane": "viper",
        "model_style": "viper_ex4",
        "animated": True,
    },
    "specter_ex4": {
        "name": "全息投影·数据流动",
        "desc": "全息图像般的存在，数据流穿梭其中，像素化与重构循环往复",
        "neon_color": (0, 255, 255),
        "accent_color": (255, 0, 255),
        "trail_color": (255, 255, 0),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "hologram",
        "particle_count": 190,
        "category": "exclusive",
        "trail_width": 19,
        "exclusive_plane": "specter",
        "model_style": "specter_ex4",
        "animated": True,
    },
    "aurora_ex4": {
        "name": "蝴蝶效应·混沌之翼",
        "desc": "蝴蝶翅膀般的混沌图案，色彩随机生成，永不重复的艺术",
        "neon_color": (255, 150, 200),
        "accent_color": (150, 200, 255),
        "trail_color": (200, 255, 150),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "butterfly_chaos",
        "particle_count": 195,
        "category": "exclusive",
        "trail_width": 25,
        "exclusive_plane": "aurora",
        "model_style": "aurora_ex4",
        "animated": True,
    },
    "crimson_ex4": {
        "name": "烟火绽放·庆典之舞",
        "desc": "如烟花般不断绽放，色彩爆炸，每一刻都是新的绚烂瞬间",
        "neon_color": (255, 50, 100),
        "accent_color": (255, 200, 50),
        "trail_color": (100, 150, 255),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "fireworks",
        "particle_count": 200,
        "category": "exclusive",
        "trail_width": 26,
        "exclusive_plane": "crimson",
        "model_style": "crimson_ex4",
        "animated": True,
    },
    "stalker_ex4": {
        "name": "迷幻漩涡·催眠螺旋",
        "desc": "催眠般的螺旋图案，色彩渐变旋转，凝视即迷失",
        "neon_color": (255, 100, 255),
        "accent_color": (100, 255, 200),
        "trail_color": (255, 200, 100),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "hypnotic_spiral",
        "particle_count": 175,
        "category": "exclusive",
        "trail_width": 23,
        "exclusive_plane": "stalker",
        "model_style": "stalker_ex4",
        "animated": True,
    },
    "gaia_ex4": {
        "name": "万花筒梦境·镜像迷宫",
        "desc": "万花筒般的对称美学，镜像无限复制，梦境般的几何奇观",
        "neon_color": (255, 180, 100),
        "accent_color": (100, 180, 255),
        "trail_color": (180, 255, 100),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "kaleidoscope",
        "particle_count": 185,
        "category": "exclusive",
        "trail_width": 24,
        "exclusive_plane": "gaia",
        "model_style": "gaia_ex4",
        "animated": True,
    },
    "weaver_ex4": {
        "name": "波动艺术·声波可视",
        "desc": "声波可视化效果，音乐般的波动，频率与振幅的视觉呈现",
        "neon_color": (100, 255, 150),
        "accent_color": (255, 150, 100),
        "trail_color": (150, 100, 255),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "waveform",
        "particle_count": 180,
        "category": "exclusive",
        "trail_width": 21,
        "exclusive_plane": "weaver",
        "model_style": "weaver_ex4",
        "animated": True,
    },
    "solar_ex4": {
        "name": "极光风暴·磁暴舞曲",
        "desc": "极光风暴般的磁场可视化，色带飘舞，能量波动如丝带般柔美",
        "neon_color": (0, 255, 150),
        "accent_color": (150, 0, 255),
        "trail_color": (255, 150, 0),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "aurora_storm",
        "particle_count": 190,
        "category": "exclusive",
        "trail_width": 25,
        "exclusive_plane": "solar",
        "model_style": "solar_ex4",
        "animated": True,
    },
    "arbiter_ex4": {
        "name": "水墨丹青·墨滴扩散",
        "desc": "中国水墨画风格，墨滴在水中扩散，渐变晕染，东方美学",
        "neon_color": (50, 50, 80),
        "accent_color": (100, 100, 150),
        "trail_color": (80, 80, 120),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "ink_diffusion",
        "particle_count": 165,
        "category": "exclusive",
        "trail_width": 22,
        "exclusive_plane": "arbiter",
        "model_style": "arbiter_ex4",
        "animated": True,
    },
    "eclipse_ex4": {
        "name": "霓虹都市·赛博脉动",
        "desc": "霓虹灯般的都市夜景，色彩跳跃闪烁，赛博朋克的电子心跳",
        "neon_color": (255, 0, 150),
        "accent_color": (0, 255, 200),
        "trail_color": (255, 200, 0),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "neon_pulse",
        "particle_count": 195,
        "category": "exclusive",
        "trail_width": 23,
        "exclusive_plane": "eclipse",
        "model_style": "eclipse_ex4",
        "animated": True,
    },
    "prism_ex4": {
        "name": "油画笔触·印象流动",
        "desc": "油画般的厚重笔触，色彩如梵高星空般流动旋转，印象派的动态诗篇",
        "neon_color": (200, 150, 100),
        "accent_color": (100, 150, 200),
        "trail_color": (150, 200, 100),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "oil_painting",
        "particle_count": 175,
        "category": "exclusive",
        "trail_width": 24,
        "exclusive_plane": "prism",
        "model_style": "prism_ex4",
        "animated": True,
    },
    "necro_ex4": {
        "name": "黑洞漩涡·引力舞蹈",
        "desc": "黑洞引力效果，时空扭曲，光线弯曲，色彩被吸入深渊般的中心",
        "neon_color": (50, 0, 100),
        "accent_color": (100, 0, 150),
        "trail_color": (80, 0, 120),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "gravity_dance",
        "particle_count": 185,
        "category": "exclusive",
        "trail_width": 26,
        "exclusive_plane": "necro",
        "model_style": "necro_ex4",
        "animated": True,
    },
}

# 读取customization.py
with open('customization.py', 'r', encoding='utf-8') as f:
    content = f.read()

# 在necro_ex3后面插入新配置
insert_marker = '''    "necro_ex3": {
        "name": "熵增极限·热寂降临",
        "desc": "宇宙热寂状态，熵值最大化，能量耗散殆尽，万物归于平静",
        "neon_color": (20, 20, 50),
        "accent_color": (50, 50, 80),
        "trail_color": (30, 30, 60),
        "unlocked": False,
        "cost": 4200,
        "trail_style": "entropy",
        "particle_count": 170,
        "category": "exclusive",
        "trail_width": 22,
        "exclusive_plane": "necro",
        "model_style": "necro_ex3",
        "animated": True,
    },'''

# 构建新的涂装配置文本
new_paints_text = ""
for key, config in paint_configs.items():
    new_paints_text += f'''
    "{key}": {{
        "name": "{config['name']}",
        "desc": "{config['desc']}",
        "neon_color": {config['neon_color']},
        "accent_color": {config['accent_color']},
        "trail_color": {config['trail_color']},
        "unlocked": {config['unlocked']},
        "cost": {config['cost']},
        "trail_style": "{config['trail_style']}",
        "particle_count": {config['particle_count']},
        "category": "{config['category']}",
        "trail_width": {config['trail_width']},
        "exclusive_plane": "{config['exclusive_plane']}",
        "model_style": "{config['model_style']}",
        "animated": {config['animated']},
    }},'''

# 插入新配置
new_content = content.replace(insert_marker, insert_marker + new_paints_text)

# 写回文件
with open('customization.py', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'✅ 成功添加16个第四批超级动态涂装配置!')
print('💎 主题：液态金属、彩虹漩涡、熔岩巨兽、等离子生命、生物荧光、全息投影、')
print('     蝴蝶效应、烟火绽放、迷幻漩涡、万花筒、波动艺术、极光风暴、')
print('     水墨丹青、霓虹都市、油画笔触、黑洞漩涡')
