# 添加第五批16个超有趣涂装配置（_ex5系列）

paint_configs = {
    "striker_ex5": {
        "name": "像素进化·8bit回忆",
        "desc": "从8bit像素进化到高清，复古游戏风格，像素方块不断重组",
        "neon_color": (255, 100, 100),
        "accent_color": (100, 255, 100),
        "trail_color": (100, 100, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "pixel_evolution",
        "particle_count": 200,
        "category": "exclusive",
        "trail_width": 20,
        "exclusive_plane": "striker",
        "model_style": "striker_ex5",
        "animated": True,
    },
    "phantom_ex5": {
        "name": "表情包战士·颜文字",
        "desc": "各种表情符号环绕，(｡◕‿◕｡)、(╯°□°）╯︵ ┻━┻，表情随战况变化",
        "neon_color": (255, 200, 100),
        "accent_color": (100, 200, 255),
        "trail_color": (255, 100, 200),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "emoji_warrior",
        "particle_count": 180,
        "category": "exclusive",
        "trail_width": 22,
        "exclusive_plane": "phantom",
        "model_style": "phantom_ex5",
        "animated": True,
    },
    "titan_ex5": {
        "name": "几何变形·欧几里得",
        "desc": "不断变换的几何图形，三角形→正方形→五边形→圆形，数学之美",
        "neon_color": (100, 255, 200),
        "accent_color": (255, 100, 150),
        "trail_color": (200, 100, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "geometry_morph",
        "particle_count": 190,
        "category": "exclusive",
        "trail_width": 23,
        "exclusive_plane": "titan",
        "model_style": "titan_ex5",
        "animated": True,
    },
    "thunderbird_ex5": {
        "name": "音游节奏·下落天堂",
        "desc": "音游下落式音符，节奏轨道，perfect判定特效，跟随音乐律动",
        "neon_color": (255, 255, 100),
        "accent_color": (255, 100, 255),
        "trail_color": (100, 255, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "rhythm_game",
        "particle_count": 210,
        "category": "exclusive",
        "trail_width": 19,
        "exclusive_plane": "thunderbird",
        "model_style": "thunderbird_ex5",
        "animated": True,
    },
    "viper_ex5": {
        "name": "魔法阵召唤·炼金术",
        "desc": "复杂魔法阵旋转，炼金符文闪烁，召唤法阵从天而降",
        "neon_color": (200, 150, 255),
        "accent_color": (255, 200, 100),
        "trail_color": (100, 255, 150),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "magic_circle",
        "particle_count": 195,
        "category": "exclusive",
        "trail_width": 24,
        "exclusive_plane": "viper",
        "model_style": "viper_ex5",
        "animated": True,
    },
    "specter_ex5": {
        "name": "故障艺术·系统崩溃",
        "desc": "屏幕故障效果，RGB分离，画面撕裂，数字失真，赛博错乱美学",
        "neon_color": (255, 0, 0),
        "accent_color": (0, 255, 0),
        "trail_color": (0, 0, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "glitch_art",
        "particle_count": 205,
        "category": "exclusive",
        "trail_width": 21,
        "exclusive_plane": "specter",
        "model_style": "specter_ex5",
        "animated": True,
    },
    "aurora_ex5": {
        "name": "折纸艺术·千纸鹤",
        "desc": "折纸风格，纸鹤飞舞，折痕线条，日式和风纸艺术",
        "neon_color": (255, 180, 180),
        "accent_color": (180, 255, 180),
        "trail_color": (180, 180, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "origami",
        "particle_count": 175,
        "category": "exclusive",
        "trail_width": 20,
        "exclusive_plane": "aurora",
        "model_style": "aurora_ex5",
        "animated": True,
    },
    "crimson_ex5": {
        "name": "弹幕地狱·东方幻想",
        "desc": "东方project风格弹幕，子弹海洋，华丽弹幕图案，美丽又危险",
        "neon_color": (255, 100, 150),
        "accent_color": (150, 100, 255),
        "trail_color": (100, 255, 150),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "bullet_hell",
        "particle_count": 220,
        "category": "exclusive",
        "trail_width": 18,
        "exclusive_plane": "crimson",
        "model_style": "crimson_ex5",
        "animated": True,
    },
    "stalker_ex5": {
        "name": "时钟齿轮·蒸汽朋克",
        "desc": "机械齿轮转动，钟表指针，蒸汽管道，维多利亚工业美学",
        "neon_color": (180, 140, 100),
        "accent_color": (220, 180, 120),
        "trail_color": (150, 110, 70),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "steampunk",
        "particle_count": 185,
        "category": "exclusive",
        "trail_width": 23,
        "exclusive_plane": "stalker",
        "model_style": "stalker_ex5",
        "animated": True,
    },
    "gaia_ex5": {
        "name": "DNA螺旋·生命密码",
        "desc": "双螺旋结构，碱基对闪烁，细胞分裂，生命的蓝图在空中编织",
        "neon_color": (100, 255, 150),
        "accent_color": (255, 150, 100),
        "trail_color": (150, 100, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "dna_helix",
        "particle_count": 200,
        "category": "exclusive",
        "trail_width": 21,
        "exclusive_plane": "gaia",
        "model_style": "gaia_ex5",
        "animated": True,
    },
    "weaver_ex5": {
        "name": "棋盘游戏·策略大师",
        "desc": "黑白棋盘，国际象棋棋子，围棋棋子，策略游戏的视觉呈现",
        "neon_color": (220, 220, 220),
        "accent_color": (50, 50, 50),
        "trail_color": (150, 150, 150),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "chess_board",
        "particle_count": 170,
        "category": "exclusive",
        "trail_width": 22,
        "exclusive_plane": "weaver",
        "model_style": "weaver_ex5",
        "animated": True,
    },
    "solar_ex5": {
        "name": "天气预报·气象万千",
        "desc": "晴天太阳、雨滴、雪花、闪电，四季天气随机切换，气象图标飞舞",
        "neon_color": (255, 220, 100),
        "accent_color": (100, 180, 255),
        "trail_color": (200, 200, 200),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "weather",
        "particle_count": 190,
        "category": "exclusive",
        "trail_width": 20,
        "exclusive_plane": "solar",
        "model_style": "solar_ex5",
        "animated": True,
    },
    "arbiter_ex5": {
        "name": "星座连线·黄道十二宫",
        "desc": "星座图案，星星连线，白羊座到双鱼座循环，占星术的神秘",
        "neon_color": (255, 255, 200),
        "accent_color": (200, 200, 255),
        "trail_color": (255, 200, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "constellation",
        "particle_count": 180,
        "category": "exclusive",
        "trail_width": 19,
        "exclusive_plane": "arbiter",
        "model_style": "arbiter_ex5",
        "animated": True,
    },
    "eclipse_ex5": {
        "name": "漫画分镜·速度线",
        "desc": "漫画效果线，爆炸泡泡，砰砰砰音效字，日漫战斗分镜效果",
        "neon_color": (255, 100, 100),
        "accent_color": (100, 100, 255),
        "trail_color": (255, 255, 100),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "manga_panel",
        "particle_count": 195,
        "category": "exclusive",
        "trail_width": 24,
        "exclusive_plane": "eclipse",
        "model_style": "eclipse_ex5",
        "animated": True,
    },
    "prism_ex5": {
        "name": "乐高积木·创意拼搭",
        "desc": "积木块堆叠，拼搭动画，彩色塑料砖，童年的创造力",
        "neon_color": (255, 50, 50),
        "accent_color": (50, 255, 50),
        "trail_color": (50, 50, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "lego_blocks",
        "particle_count": 185,
        "category": "exclusive",
        "trail_width": 22,
        "exclusive_plane": "prism",
        "model_style": "prism_ex5",
        "animated": True,
    },
    "necro_ex5": {
        "name": "俄罗斯方块·消除爆炸",
        "desc": "下落的方块，消除特效，旋转堆叠，经典游戏致敬",
        "neon_color": (100, 255, 255),
        "accent_color": (255, 255, 100),
        "trail_color": (255, 100, 255),
        "unlocked": False,
        "cost": 4800,
        "trail_style": "tetris",
        "particle_count": 200,
        "category": "exclusive",
        "trail_width": 21,
        "exclusive_plane": "necro",
        "model_style": "necro_ex5",
        "animated": True,
    },
}

# 读取customization.py
with open('customization.py', 'r', encoding='utf-8') as f:
    content = f.read()

# 在necro_ex4后面插入新配置
insert_marker = '''    "necro_ex4": {
        "name": "黑洞漩涡·引力舞蹈",
        "desc": "黑洞引力效果，时空扭曲，光线弯曲，色彩被吸入深渊般的中心",
        "neon_color": (50, 0, 100),
        "accent_color": (100, 0, 150),
        "trail_color": (80, 0, 120),
        "unlocked": False,
        "cost": 4500,
        "trail_style": "gravity_dance",
        "particle_count": 185,
        "category": "exclusive",
        "trail_width": 26,
        "exclusive_plane": "necro",
        "model_style": "necro_ex4",
        "animated": True,
    },'''

# 构建新的涂装配置文本
new_paints_text = ""
for key, config in paint_configs.items():
    new_paints_text += f'''
    "{key}": {{
        "name": "{config['name']}",
        "desc": "{config['desc']}",
        "neon_color": {config['neon_color']},
        "accent_color": {config['accent_color']},
        "trail_color": {config['trail_color']},
        "unlocked": {config['unlocked']},
        "cost": {config['cost']},
        "trail_style": "{config['trail_style']}",
        "particle_count": {config['particle_count']},
        "category": "{config['category']}",
        "trail_width": {config['trail_width']},
        "exclusive_plane": "{config['exclusive_plane']}",
        "model_style": "{config['model_style']}",
        "animated": {config['animated']},
    }},'''

# 插入新配置
new_content = content.replace(insert_marker, insert_marker + new_paints_text)

# 写回文件
with open('customization.py', 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f'✅ 成功添加16个第五批超有趣涂装配置!')
print('🎮 主题：像素进化、表情包、几何变形、音游节奏、魔法阵、故障艺术、')
print('       折纸、弹幕地狱、蒸汽朋克、DNA螺旋、棋盘、天气、')
print('       星座、漫画、乐高、俄罗斯方块')
